version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: qlct
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-database:
